#ShowPlayerHP Config
version: 1.2
#DON'T EDIT!!!

#Show:
  # 1 = It only shows you health when you hit it with a projectile
  # 2 = It shows your health when you hit it with anything

Show: 2

#Type:
  # 0 = Disable Show HP
  # 1 = Default, show numeric HP
  # 2 = Show Player HP in Hreat Emoji(Hypixel)

Type: 2

#Format type:
  # 1 = Send Player Message with Attacked player HP
  # 2 = Send Player Popup with Attacked player HP
  # 3 = Send Player Title with Attacked player HP

Format: 2

#Message:
  # (optional)Use for Heart = ❤
  # (optional)Use for Color = §
  # @name = Player name
  # @hp = Player HP

MessageHP: "§l§e@name §cis now in§e @hp §cHP"
PopupHP: "§l§7@name§c @hp §4❤"
TitleHP: "§l§b@name §r§c\n@hp §4❤"
