#ShowProjectileHP Config

#Format type:
  # 0 = Disable Show HP
  # 1 = Send Player Message with Attacked player HP
  # 2 = Send Player Popup with Attacked player HP
  # 3 = Send Player Title with Attacked player HP

Format: 1

#Message:
  # Use for Heart = ❤
  # Use for Color = §
  # @name = Player name
  # @hp = Player HP

MessageHP: "§b @name §7is now in§c @hp §2❤"
Popup: "§7 @name §c @hp §2❤"
Title: "§b @name §c\n @hp §2❤"